name: 'ffmpeg build Windows'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  msvc:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Install dependencies
      shell: bash
      run: |
        git clone --depth 1 https://github.com/Microsoft/vcpkg
        touch ffmpeg_build.json

    - name: Upload the results
      uses: actions/upload-artifact@v2
      with:
        name: ffmpeg_build
        path: ffmpeg_build.json