name: 'tests Mac'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  macos-static:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        brew install meson ninja
        brew install sdl2
        brew install ffmpeg
        brew install pkg-config

    - name: Run tests
      run: |
        meson setup --buildtype release builddir --default-library static
        meson test -C builddir -v

    - name: Upload Logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: macos-static-logs
        path: builddir/meson-logs

  macos-shared:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        brew install meson ninja
        brew install sdl2
        brew install ffmpeg
        brew install pkg-config

    - name: Run tests
      run: |
        meson setup --buildtype release builddir --default-library shared
        meson test -C builddir -v

    - name: Upload Logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: macos-shared-logs
        path: builddir/meson-logs
