name: 'tests Windows'

on:
  push:
    branches:
      - 'main'
  pull_request:
  schedule:
      - cron: "0 0 * * 6"  # Run every Saturday at midnight

jobs:
  mingw-static:

    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:

      - uses: actions/checkout@v2

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64 # Start a 64 bit Mingw environment
          update: true

      - name: Install dependencies
        run: |
          pacman -S --noconfirm --needed git
          pacman -S --noconfirm --needed mingw-w64-x86_64-{toolchain,ffmpeg}
          pacman -S --noconfirm mingw-w64-x86_64-python3-pip
          pacman -S --noconfirm --needed mingw-w64-x86_64-meson

      - name: Setup
        run: |
          meson setup builddir --default-library static -Dplayer=disabled

      - name: Build
        run: |
          meson compile -C builddir

      - name: Test
        run: |
          meson test -C builddir

      - name: Upload Logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: mingw-static-logs
          path: builddir/meson-logs


  mingw-shared:

    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:

      - uses: actions/checkout@v2

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64 # Start a 64 bit Mingw environment
          update: true

      - name: Install dependencies
        run: |
          pacman -S --noconfirm --needed git
          pacman -S --noconfirm --needed mingw-w64-x86_64-{toolchain,ffmpeg}
          pacman -S --noconfirm mingw-w64-x86_64-python3-pip
          pacman -S --noconfirm --needed mingw-w64-x86_64-meson

      - name: Setup
        run: |
          meson setup builddir --default-library shared

      - name: Build
        run: |
          meson compile -C builddir

      - name: Test
        run: |
          meson test -C builddir

      - name: Upload Logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: mingw-shared-logs
          path: builddir/meson-logs


  msvc-static:

    runs-on: windows-latest
    env:
      VCPKG_TRIPLET: x64-windows
      VCPKG_INSTALL_PACKAGES: ffmpeg[ffmpeg]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Install meson and pkg-config
      shell: bash
      run: |
        pip install meson
        choco install --allow-empty-checksums pkgconfiglite

    - name: Get vcpkg cache key
      shell: bash
      id: get-vcpkg-cache-key
      run: |
        VCPKG_COMMIT_ID=$(git -C C:/vcpkg rev-parse HEAD)
        echo "::set-output name=key::$(echo $VCPKG_COMMIT_ID ${{env.VCPKG_TRIPLET}} ${{env.VCPKG_INSTALL_PACKAGES}} | md5sum | cut -f1 -d" ")"

    - name: Restore vcpkg binary cache archives
      id: restore_vcpkg_binary_cache
      uses: actions/cache@v2
      with:
        path: C:\Users\runneradmin\AppData\Local\vcpkg\archives
        key: ${{ steps.get-vcpkg-cache-key.outputs.key }}

    - name: Install dependencies
      run: |
        cd C:\vcpkg
        .\vcpkg.exe install --triplet ${{env.VCPKG_TRIPLET}} ${{env.VCPKG_INSTALL_PACKAGES}}

    - name: Setup
      shell: cmd
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" x64 && ^
        meson setup builddir --backend vs --buildtype release --default-library static ^
        --pkg-config-path "C:\vcpkg\installed\x64-windows\lib\pkgconfig"

    - name: Build
      shell: cmd
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" x64 && ^
        meson compile -C builddir

    - name: Test
      shell: cmd
      run: |
        set PATH=C:\vcpkg\installed\x64-windows\bin;%PATH%
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" x64 && ^
        meson test -C builddir

    - name: Upload Logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: msvc-static-logs
        path: builddir/meson-logs


  msvc-shared:

    runs-on: windows-latest
    env:
      VCPKG_TRIPLET: x64-windows
      VCPKG_INSTALL_PACKAGES: ffmpeg[ffmpeg]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Install meson and pkg-config
      shell: bash
      run: |
        pip install meson
        choco install --allow-empty-checksums pkgconfiglite

    - name: Get vcpkg cache key
      shell: bash
      id: get-vcpkg-cache-key
      run: |
        VCPKG_COMMIT_ID=$(git -C C:/vcpkg rev-parse HEAD)
        echo "::set-output name=key::$(echo $VCPKG_COMMIT_ID ${{env.VCPKG_TRIPLET}} ${{env.VCPKG_INSTALL_PACKAGES}} | md5sum | cut -f1 -d" ")"

    - name: Restore vcpkg binary cache archives
      id: restore_vcpkg_binary_cache
      uses: actions/cache@v2
      with:
        path: C:\Users\runneradmin\AppData\Local\vcpkg\archives
        key: ${{ steps.get-vcpkg-cache-key.outputs.key }}

    - name: Install dependencies
      run: |
        cd C:\vcpkg
        .\vcpkg.exe install --triplet ${{env.VCPKG_TRIPLET}} ${{env.VCPKG_INSTALL_PACKAGES}}

    - name: Setup
      shell: cmd
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" x64 && ^
        meson setup builddir --backend vs --buildtype release --default-library shared ^
        --pkg-config-path "C:\vcpkg\installed\x64-windows\lib\pkgconfig"

    - name: Build
      shell: cmd
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" x64 && ^
        meson compile -C builddir

    - name: Test
      shell: cmd
      run: |
        set PATH=C:\vcpkg\installed\x64-windows\bin;%PATH%
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" x64 && ^
        meson test -C builddir

    - name: Upload Logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: msvc-shared-logs
        path: builddir/meson-logs
